name: parktiv
region: fra
services:
- build_command: pip3 install --no-cache-dir -r requirements.txt
  environment_slug: python
  github:
    branch: master
    deploy_on_push: true
    repo: leonharj-fh/parktiv
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: parktiv
  routes:
  - path: /
  run_command: python -m parktiv_server
  source_dir: /
