# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from parktiv_server.models.base_model_ import Model
from parktiv_server.models.task import Task
from parktiv_server.models.image import Image
from parktiv_server import util
import re


class Animal(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, title: str=None, image: Image=None, tasks: List[Task]=None):  # noqa: E501
        """Animal - a model defined in Swagger

        :param id: The id of this Animal.  # noqa: E501
        :type id: str
        :param title: The title of this Animal.  # noqa: E501
        :type title: str
        :param image: The image of this Animal.  # noqa: E501
        :type image: Image
        :param tasks: The tasks of this Animal.  # noqa: E501
        :type tasks: List[Task]
        """
        self.swagger_types = {
            'id': str,
            'title': str,
            'image': Image,
            'tasks': List[Task]
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'image': 'image',
            'tasks': 'tasks'
        }

        self._id = id
        self._title = title
        self._image = image
        self._tasks = tasks

    @classmethod
    def from_dict(cls, dikt) -> 'Animal':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Animal of this Animal.  # noqa: E501
        :rtype: Animal
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Animal.


        :return: The id of this Animal.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Animal.


        :param id: The id of this Animal.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and len(id) < 1:
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `1`")  # noqa: E501
        if id is not None and not re.search(r'^[a-zA-Z0-9_-]{1,30}$', id):  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]{1,30}$/`")  # noqa: E501

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Animal.


        :return: The title of this Animal.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Animal.


        :param title: The title of this Animal.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501
        if title is not None and len(title) < 1:
            raise ValueError("Invalid value for `title`, length must be greater than or equal to `1`")  # noqa: E501

        self._title = title

    @property
    def image(self) -> Image:
        """Gets the image of this Animal.


        :return: The image of this Animal.
        :rtype: Image
        """
        return self._image

    @image.setter
    def image(self, image: Image):
        """Sets the image of this Animal.


        :param image: The image of this Animal.
        :type image: Image
        """

        self._image = image

    @property
    def tasks(self) -> List[Task]:
        """Gets the tasks of this Animal.


        :return: The tasks of this Animal.
        :rtype: List[Task]
        """
        return self._tasks

    @tasks.setter
    def tasks(self, tasks: List[Task]):
        """Sets the tasks of this Animal.


        :param tasks: The tasks of this Animal.
        :type tasks: List[Task]
        """
        if tasks is None:
            raise ValueError("Invalid value for `tasks`, must not be `None`")  # noqa: E501

        self._tasks = tasks
