# coding: utf-8

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from parktiv_server.models.base_model_ import Model
from parktiv_server.models.animal import Animal
from parktiv_server import util


class AnimalResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, animals: List[Animal]=None):  # noqa: E501
        """AnimalResponse - a model defined in Swagger

        :param animals: The animals of this AnimalResponse.  # noqa: E501
        :type animals: List[Animal]
        """
        self.swagger_types = {
            'animals': List[Animal]
        }

        self.attribute_map = {
            'animals': 'animals'
        }
        self._animals = animals

    @classmethod
    def from_dict(cls, dikt) -> 'AnimalResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnimalResponse of this AnimalResponse.  # noqa: E501
        :rtype: AnimalResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def animals(self) -> List[Animal]:
        """Gets the animals of this AnimalResponse.

        List of animals  # noqa: E501

        :return: The animals of this AnimalResponse.
        :rtype: List[Animal]
        """
        return self._animals

    @animals.setter
    def animals(self, animals: List[Animal]):
        """Sets the animals of this AnimalResponse.

        List of animals  # noqa: E501

        :param animals: The animals of this AnimalResponse.
        :type animals: List[Animal]
        """

        self._animals = animals
