# coding: utf-8

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from parktiv_server.models.base_model_ import Model
from parktiv_server import util



class MemoryResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ids: List[str]=None):  # noqa: E501
        """MemoryResponse - a model defined in Swagger

        :param ids: The ids of this MemoryResponse.  # noqa: E501
        :type ids: List[str]
        """
        self.swagger_types = {
            'ids': List[str]
        }

        self.attribute_map = {
            'ids': 'ids'
        }
        self._ids = ids

    @classmethod
    def from_dict(cls, dikt) -> 'MemoryResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MemoryResponse of this MemoryResponse.  # noqa: E501
        :rtype: MemoryResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ids(self) -> List[str]:
        """Gets the ids of this MemoryResponse.


        :return: The ids of this MemoryResponse.
        :rtype: List[str]
        """
        return self._ids

    @ids.setter
    def ids(self, ids: List[str]):
        """Sets the ids of this MemoryResponse.


        :param ids: The ids of this MemoryResponse.
        :type ids: List[str]
        """
        if ids is None:
            raise ValueError("Invalid value for `ids`, must not be `None`")  # noqa: E501

        self._ids = ids
