# coding: utf-8


from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from parktiv_server.models.base_model_ import Model
from parktiv_server.models.park import Park
from parktiv_server import util


class ParksResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, parks: List[Park]=None):  # noqa: E501
        """ParksResponse - a model defined in Swagger

        :param parks: The parks of this ParksResponse.  # noqa: E501
        :type parks: List[Park]
        """
        self.swagger_types = {
            'parks': List[Park]
        }

        self.attribute_map = {
            'parks': 'parks'
        }

        self._parks = parks

    @classmethod
    def from_dict(cls, dikt) -> 'ParksResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParksResponse of this ParksResponse.  # noqa: E501
        :rtype: ParksResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def parks(self) -> List[Park]:
        """Gets the parks of this ParksResponse.


        :return: The parks of this ParksResponse.
        :rtype: List[Park]
        """
        return self._parks

    @parks.setter
    def parks(self, parks: List[Park]):
        """Sets the parks of this ParksResponse.


        :param parks: The parks of this ParksResponse.
        :type parks: List[Park]
        """

        self._parks = parks
