# coding: utf-8


from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from parktiv_server.models.base_model_ import Model
from parktiv_server.models.role import Role
from parktiv_server import util


class RoleResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, roles: List[Role]=None):  # noqa: E501
        """RoleResponse - a model defined in Swagger

        :param roles: The roles of this RoleResponse.  # noqa: E501
        :type roles: List[Role]
        """
        self.swagger_types = {
            'roles': List[Role]
        }

        self.attribute_map = {
            'roles': 'roles'
        }

        self._roles = roles

    @classmethod
    def from_dict(cls, dikt) -> 'RoleResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoleResponse of this RoleResponse.  # noqa: E501
        :rtype: RoleResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def roles(self) -> List[Role]:
        """Gets the roles of this RoleResponse.


        :return: The roles of this RoleResponse.
        :rtype: List[Role]
        """
        return self._roles

    @roles.setter
    def roles(self, roles: List[Role]):
        """Sets the roles of this RoleResponse.


        :param roles: The roles of this RoleResponse.
        :type roles: List[Role]
        """

        self._roles = roles
