%YAML 1.2
---

animals:
  - id: elephant
    title: Elephant
    image: Url
    taskCategory: Empowerment
    tasks: 
      - roleId: flink
        exercise: Stampfe in den Boden wie der Elefant, mache dich dabei groß wie ein Elefant.
        audio: Url
      - roleId: geschickt
        exercise: Strecke deine Arme zur Seite, wie die Ohren des Elefanten und schwinge langsam nach hinten und vorne.
        audio: Url

...