%YAML 1.2
---

animals:
  - id: elephant
    title: Elephant
    image: Url
    taskCategory: Empowerment
    tasks:
      - roleId: flink
        exercise: Stampfe in den Boden wie der Elefant, mache dich dabei groß wie ein Elefant.
        audio: Url
      - roleId: geschickt
        exercise: Strecke deine Arme zur Seite, wie die Ohren des Elefanten und schwinge langsam nach hinten und vorne.
        audio: Url
  - id: giraffe
    title: Giraffe
    image: N/A
    tasks:
      - roleId: flink
        exercise: mach dich groß wie die Giraffe, versuche dabei mit den Händen, vorgestellte Blätter, die ganz hoch oben hängen zu erwischen
      - roleId: geschickt
        exercise: mach dich groß wie die Giraffe, versuche dabei mit den Händen, vorgestellte Blätter, die ganz hoch oben hängen zu erwischen
  - id: affe
    title: Affe
    image: N/A
    taskCategory: "Koordination, Balance"
    tasks:
      - roleId: flink
        exercise: stell dir vor du kletterst auf einen Baum, mach die Bewegung dazu in der Luft nach. Schaffst du es die Beine und Arme jeweils diagonal hochzuheben?
      - roleId: geschickt
        exercise: setze einen Fuß vor den anderen und gehe auf einer gedachten Linie, wie wenn du über einen Ast balancierst
  - id: kaenguruh
    title: Känguruh
    taskCategory: "hüpfen, boxen"
    tasks:
      - roleId: flink
        exercise: mache 10 Känguruhsprünge, versuche dabei die Knie bis zur Brust hoch zu ziehen
      - roleId: geschickt
        exercise: 2 Känguruhs haben einen Revierkampf, boxe mit deinen Armen in die Luft um das andere Känguruh zu vertreiben


...