%YAML 1.2
---

animals:
  - id: elephant
    title: Elephant
    image:
      url: "elephant.png"
      copyright: "<a href=\"http://www.freepik.com\">Designed by brgfx / Freepik</a>"
    taskCategory: Empowerment
    tasks:
      - roleId: faenger
        exercise: Stampfe in den Boden wie der Elefant, mache dich dabei groß wie ein Elefant.
        audio: Url
      - roleId: koordinator
        exercise: Strecke deine Arme zur Seite, wie die Ohren des Elefanten und schwinge langsam nach hinten und vorne.
        audio: Url
  - id: giraffe
    title: Giraffe
    image:
      url: "giraffe.png"
      copyright: "<a href=\"http://www.freepik.com\">Designed by winkimages / Freepik</a>"
    tasks:
      - roleId: faenger
        exercise: Mach dich groß wie die Giraffe, versuche dabei mit den Händen, vorgestellte Blätter, die ganz hoch oben hängen zu erwischen
      - roleId: koordinator
        exercise: Mach dich groß wie die Giraffe, versuche dabei mit den Händen, vorgestellte Blätter, die ganz hoch oben hängen zu erwischen
  - id: affe
    title: Affe
    image:
      url: "affe.png"
      copyright: "<a href=\"http://www.freepik.com\">Designed by pch.vector / Freepik</a>"
    taskCategory: "Koordination, Balance"
    tasks:
      - roleId: faenger
        exercise: Stell dir vor du kletterst auf einen Baum, mach die Bewegung dazu in der Luft nach. Schaffst du es die Beine und Arme jeweils diagonal hochzuheben?
      - roleId: koordinator
        exercise: Setze einen Fuß vor den anderen und gehe auf einer gedachten Linie, wie wenn du über einen Ast balancierst.
  - id: kaenguruh
    title: Känguruh
    image:
      url: "kaenguruh.png"
      copyright: "<a href=\"http://www.freepik.com\">Designed by Ajipebriana / Freepik</a>"
    taskCategory: "hüpfen, boxen"
    tasks:
      - roleId: faenger
        exercise: Mache 10 Känguruhsprünge, versuche dabei die Knie bis zur Brust hoch zu ziehen.
      - roleId: koordinator
        exercise: 2 Känguruhs haben einen Revierkampf, boxe mit deinen Armen in die Luft um das andere Känguruh zu vertreiben.


...